version: '3'
services:
  rss2tg:
    container_name: rss2tg
    image: drfyup/rss2tg:latest
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN=tg bot token
      - TELEGRAM_USERS=tg user id
      - TELEGRAM_CHANNELS=tg channel id
      - TZ=Asia/Shanghai
    restart: unless-stopped
