name: Deploy to Hugging Face Spaces

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Hugging Face Docker registry
      uses: docker/login-action@v2
      with:
        registry: "https://huggingface.co"
        username: "${{ secrets.HF_USERNAME }}"
        password: "${{ secrets.HF_TOKEN }}"

    - name: Build and Push Docker image
      run: |
        docker build -t huggingface.co/spaces/drfy/rss2tg .
        docker push huggingface.co/spaces/drfy/rss2tg
