name: Deploy to Hugging Face Spaces

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        SPACE_ID: your_hf_space_id
      run: |
        # 安装 Hugging Face hub CLI 工具
        pip install huggingface_hub

        # 将指定的镜像推送到Hugging Face
        huggingface-cli space deploy --docker-image drfyup/rss2tg:latest $SPACE_ID --token $HF_TOKEN
